### ISSUE TITLE
Idea about the database

### ISSUE THREAD

**Issue by Shaneumayanga** [GolangSriLanka/go-puso#5]
I believe that the database.Database() which returns *gorm.DB should only be called once, and the DB variable should be long-lived, since the database.Database() is called multiple times in transact\puso\puso_model.go I guess it is inefficient?  I suggest having an interface with the methods that have the CRUD operations and a struct that implements it with a DB *gorm.DB as a struct variable

Like so:

```go
package main
type Repo interface {
	SavePUSO(puso *models.Pusa) error
}

type repo struct{
	db *gorm.DB
}

func NewPOSORepo(db *gorm.DB) *repo{
	return &repo{
		db:db,
	}
}

func (repo *repo) SavePUSO(puso *models.Pusa) error{
	err := repo.db.Create(puso)
	if err != nil{
		return err
	}
	return nil
}
```

And you can have a controller that handles the HTTP handlers which has a PusaREPO which calls to the CRUD methods, this approach also allows you to have multiple implementations of the PUSArepo that uses different databases like MongoDB

**Comment by sithumonline** [comment]
We have truly missed the interface 😿. It's really nice to implement, can you work on it @Shaneumayanga? 🙊

**Comment by Shaneumayanga** [comment]
> We have truly missed the interface 😿. It's really nice to implement, can you work on it @Shaneumayanga? 🙊 

Sure will 😼😼😼😻
